print ("Quel est votre prénom?")
prenom=input ()
print ("Quel est votre date de naissance?")
print ("jour (entre 1 et 31)?")
j=input ()
print ("mois (entre 1 et 12)?")
m=input ()
print ("année?")
a=input()
agea=2017 - int(a)
agem=3 - int(m)
agej=25 - int(j)
print (prenom ,",tu as" ,agea ,"ans", agem, "mois et", agej,"jours!")
